[pytest]
markers =
    sanity: Sanity Test Cases
    regression: Regression Test Cases
    bottom_navigation_menu: bottom_navigation_menu
    android_and_ios: android_and_ios
    mobile: mobile
    signup:signup

addopts = -rA -v