[common info]

email = testautomation@mailinator.com
password = Test@123
newpassword = Test@1234

[device_1]
package = com.katonmeet.qa
activity = com.katonmeet.activity.WelcomeActivity
platform_name = Android
platform_version = 13
device_name = Galaxy F62
; udid = 205fofbb0409
udid = RZ8R60G7WCK
; udid = RF8M32M3T6E
automator_name = UiAutomator2
port = 4723
;
[device_2]
package = com.greencopper.revoltmusicconference2022.staging
activity = com.greencopper.revoltmusicconference2022.MainActivity
platform_name = Android
platform_version = 12
device_name = A31
; udid = 205fofbb0409
udid = RZ8N602HQVT
; udid = RF8M32M3T6E
automator_name = UiAutomator2
port = 4720